application: screamphone
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /sounds
  static_dir: sounds
- url: /bootstrap
  static_dir: bootstrap
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: django
  version: 1.3

builtins:
- remote_api: on

# inbound_services:
# - warmup
